"""standarize prices

Revision ID: 0b6f8a1cb481
Revises: 07e1e75def84
Create Date: 2026-03-07 03:04:50.038086

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b6f8a1cb481"
down_revision: str | None = "07e1e75def84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customers",
        "credit_limit",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=True,
    )
    op.alter_column(
        "payments",
        "amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "purchase_price",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "sale_price",
        existing_type=sa.NUMERIC(precision=12, scale=4),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=True,
    )
    op.alter_column(
        "purchase_order_items",
        "unit_cost",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "purchase_orders",
        "subtotal",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "purchase_orders",
        "tax",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "purchase_orders",
        "total",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "sale_items",
        "unit_price",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "sales",
        "subtotal",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "sales",
        "tax",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "sales",
        "discount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "sales",
        "total",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "supplier_products",
        "purchase_price",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "supplier_products",
        "purchase_price",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "sales",
        "total",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "sales",
        "discount",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "sales",
        "tax",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "sales",
        "subtotal",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "sale_items",
        "unit_price",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "purchase_orders",
        "total",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "purchase_orders",
        "tax",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "purchase_orders",
        "subtotal",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "purchase_order_items",
        "unit_cost",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "sale_price",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "purchase_price",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=4),
        existing_nullable=True,
    )
    op.alter_column(
        "payments",
        "amount",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "customers",
        "credit_limit",
        existing_type=sa.Numeric(precision=12, scale=6),
        type_=sa.NUMERIC(precision=12, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
