"""add parked_at park_reason to sales

Revision ID: 203cacde507b
Revises: b00cb1ea390e
Create Date: 2026-03-14 14:09:59.522953

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "203cacde507b"
down_revision: str | None = "b00cb1ea390e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sales", sa.Column("parked_at", sa.DateTime(), nullable=True))
    op.add_column(
        "sales", sa.Column("park_reason", sa.String(length=512), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sales", "park_reason")
    op.drop_column("sales", "parked_at")
    # ### end Alembic commands ###
