"""create pos_refunds pos_refund_items pos_refund_payments tables

Revision ID: 306672eb2a0e
Revises: 58487ca98217
Create Date: 2026-03-14 22:49:13.961570

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "306672eb2a0e"
down_revision: str | None = "58487ca98217"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pos_refunds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("original_sale_id", sa.Integer(), nullable=False),
        sa.Column("shift_id", sa.Integer(), nullable=True),
        sa.Column("refund_date", sa.DateTime(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("tax", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("reason", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("refunded_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["original_sale_id"],
            ["sales.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["pos_shifts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pos_refund_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("refund_id", sa.Integer(), nullable=False),
        sa.Column("original_sale_item_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("discount", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["original_sale_item_id"],
            ["sale_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(["refund_id"], ["pos_refunds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pos_refund_payments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("refund_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("payment_method", sa.String(length=16), nullable=False),
        sa.Column("reference", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["refund_id"], ["pos_refunds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pos_refund_payments")
    op.drop_table("pos_refund_items")
    op.drop_table("pos_refunds")
    # ### end Alembic commands ###
