"""create units_of_measure table and enhance products

Revision ID: 342b2ecf1258
Revises: 59e88fa04417
Create Date: 2026-02-22 00:54:57.894167

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "342b2ecf1258"
down_revision: str | None = "59e88fa04417"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "units_of_measure",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol"),
    )
    op.add_column("products", sa.Column("barcode", sa.String(length=64), nullable=True))
    op.add_column(
        "products",
        sa.Column("purchase_price", sa.Numeric(precision=12, scale=4), nullable=True),
    )
    op.add_column(
        "products",
        sa.Column("sale_price", sa.Numeric(precision=12, scale=4), nullable=True),
    )
    op.add_column(
        "products",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        "products",
        sa.Column(
            "is_service", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "min_stock", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column("products", sa.Column("max_stock", sa.Integer(), nullable=True))
    op.add_column(
        "products",
        sa.Column(
            "reorder_point", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column("products", sa.Column("lead_time_days", sa.Integer(), nullable=True))
    op.add_column(
        "products", sa.Column("unit_of_measure_id", sa.Integer(), nullable=True)
    )
    op.create_unique_constraint(None, "products", ["barcode"])
    op.create_foreign_key(
        None, "products", "units_of_measure", ["unit_of_measure_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_constraint(None, "products", type_="unique")
    op.drop_column("products", "unit_of_measure_id")
    op.drop_column("products", "lead_time_days")
    op.drop_column("products", "reorder_point")
    op.drop_column("products", "max_stock")
    op.drop_column("products", "min_stock")
    op.drop_column("products", "is_service")
    op.drop_column("products", "is_active")
    op.drop_column("products", "sale_price")
    op.drop_column("products", "purchase_price")
    op.drop_column("products", "barcode")
    op.drop_table("units_of_measure")
    # ### end Alembic commands ###
