"""create pos_shifts table

Revision ID: 3bfdf9327e42
Revises: 0b6f8a1cb481
Create Date: 2026-03-11 23:31:57.621982

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bfdf9327e42"
down_revision: str | None = "0b6f8a1cb481"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pos_shifts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cashier_name", sa.String(length=128), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("opening_balance", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("closing_balance", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("expected_balance", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("discrepancy", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pos_shifts")
    # ### end Alembic commands ###
