"""phase 2 - warehouses, locations, stock multi-location, enhance movements

Revision ID: 49b16d5da943
Revises: 342b2ecf1258
Create Date: 2026-02-22 01:14:33.895310

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49b16d5da943"
down_revision: str | None = "342b2ecf1258"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "warehouses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("address", sa.String(length=256), nullable=True),
        sa.Column("city", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("manager", sa.String(length=128), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "STORAGE",
                "RECEIVING",
                "SHIPPING",
                "QUALITY",
                "DAMAGED",
                name="locationtype",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_id", "code", name="uq_location_warehouse_code"),
    )
    op.add_column("movements", sa.Column("location_id", sa.Integer(), nullable=True))
    op.add_column(
        "movements", sa.Column("source_location_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "movements", sa.Column("reference_type", sa.String(length=64), nullable=True)
    )
    op.add_column("movements", sa.Column("reference_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "movements", "locations", ["location_id"], ["id"])
    op.create_foreign_key(
        None, "movements", "locations", ["source_location_id"], ["id"]
    )
    op.add_column("stocks", sa.Column("location_id", sa.Integer(), nullable=True))
    op.add_column(
        "stocks",
        sa.Column(
            "reserved_quantity", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.create_unique_constraint(
        "uq_stock_product_location", "stocks", ["product_id", "location_id"]
    )
    op.create_foreign_key(None, "stocks", "locations", ["location_id"], ["id"])
    op.drop_column("stocks", "location")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stocks",
        sa.Column(
            "location", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "stocks", type_="foreignkey")
    op.drop_constraint("uq_stock_product_location", "stocks", type_="unique")
    op.drop_column("stocks", "reserved_quantity")
    op.drop_column("stocks", "location_id")
    op.drop_constraint(None, "movements", type_="foreignkey")
    op.drop_constraint(None, "movements", type_="foreignkey")
    op.drop_column("movements", "reference_id")
    op.drop_column("movements", "reference_type")
    op.drop_column("movements", "source_location_id")
    op.drop_column("movements", "location_id")
    op.drop_table("locations")
    op.drop_table("warehouses")
    # ### end Alembic commands ###
