"""add tax_rate to products and sale_items add discount fields to sales

Revision ID: 58487ca98217
Revises: 203cacde507b
Create Date: 2026-03-14 14:24:10.296744

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58487ca98217"
down_revision: str | None = "203cacde507b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "tax_rate",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
            server_default="12.00",
        ),
    )
    op.add_column(
        "sale_items",
        sa.Column(
            "tax_rate",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
            server_default="0.00",
        ),
    )
    op.add_column(
        "sale_items",
        sa.Column(
            "tax_amount",
            sa.Numeric(precision=12, scale=6),
            nullable=False,
            server_default="0.000000",
        ),
    )
    op.add_column(
        "sales", sa.Column("discount_type", sa.String(length=16), nullable=True)
    )
    op.add_column(
        "sales",
        sa.Column(
            "discount_value",
            sa.Numeric(precision=12, scale=6),
            nullable=False,
            server_default="0.000000",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sales", "discount_value")
    op.drop_column("sales", "discount_type")
    op.drop_column("sale_items", "tax_amount")
    op.drop_column("sale_items", "tax_rate")
    op.drop_column("products", "tax_rate")
    # ### end Alembic commands ###
