"""add price_override and override_reason to sale_items

Revision ID: a355b8c15a63
Revises: f621cacb414d
Create Date: 2026-03-15 00:07:25.575948

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a355b8c15a63"
down_revision: str | None = "f621cacb414d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sale_items",
        sa.Column("price_override", sa.Numeric(precision=12, scale=6), nullable=True),
    )
    op.add_column(
        "sale_items", sa.Column("override_reason", sa.String(length=512), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sale_items", "override_reason")
    op.drop_column("sale_items", "price_override")
    # ### end Alembic commands ###
