"""add shift_id and is_final_consumer to sales make customer_id nullable

Revision ID: b00cb1ea390e
Revises: 3bfdf9327e42
Create Date: 2026-03-13 13:45:19.984845

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b00cb1ea390e"
down_revision: str | None = "3bfdf9327e42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sales",
        sa.Column(
            "is_final_consumer",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column("sales", sa.Column("shift_id", sa.Integer(), nullable=True))
    op.alter_column("sales", "customer_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_foreign_key(None, "sales", "pos_shifts", ["shift_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sales", type_="foreignkey")
    op.alter_column("sales", "customer_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("sales", "shift_id")
    op.drop_column("sales", "is_final_consumer")
    # ### end Alembic commands ###
