"""create pos_cash_movements table

Revision ID: f621cacb414d
Revises: 306672eb2a0e
Create Date: 2026-03-14 23:22:33.264405

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f621cacb414d"
down_revision: str | None = "306672eb2a0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pos_cash_movements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("shift_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("reason", sa.String(length=512), nullable=True),
        sa.Column("performed_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["pos_shifts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pos_cash_movements")
    # ### end Alembic commands ###
